// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwT-nrm2zqPUMPZLUDHoT7qZ3x0qAKBV4',
    appId: '1:737325074723:web:6277026b7a513a2ae76496',
    messagingSenderId: '737325074723',
    projectId: 'medical-order-management',
    authDomain: 'medical-order-management.firebaseapp.com',
    storageBucket: 'medical-order-management.firebasestorage.app',
    measurementId: 'G-S82Y8NDLDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgxq41lQ15Kl5Qx6F76yW64_Yjrz0ZN-c',
    appId: '1:737325074723:android:3a087b3bf680bda5e76496',
    messagingSenderId: '737325074723',
    projectId: 'medical-order-management',
    storageBucket: 'medical-order-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7DDDIamVjLHd3rsgB7vtLEOw9iU7XTPA',
    appId: '1:737325074723:ios:007aab46dd0afef2e76496',
    messagingSenderId: '737325074723',
    projectId: 'medical-order-management',
    storageBucket: 'medical-order-management.firebasestorage.app',
    iosBundleId: 'com.medicalorder.medicalOrderManagement',
  );
}
